version: '3.8'

#Define services
services:

  #PostgreSQL Database for the application
  sms-postgres:
    image: "postgres:12"
    restart: always
    container_name: sms-postgres

    #Environment variable for DB name, user and password
    environment:
      - POSTGRES_DB=sms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=TodayisJune5
    
    #Volume mounted for database for the storage
    volumes:
      - type: bind
        source: ./sms-data/
        target: /var/lib/postgresql/data/

    ports:
      - 5432:5432 # Forward the exposed port 5432 on the container to port 5432 on the host machine

  #Back-end Spring Boot Application
  sms-backend:
    #The docker file in sms-backend build the jar and provides the docker image with the following name.
    image: "ajinkyadhote/sms-fs_sms-backend:v1"
    container_name: sms-backend

    #Environment variables for Spring Boot Application.
    environment:
      - DB_SERVER=sms-postgres
      - POSTGRES_DB=sms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=TodayisJune5
    ports:
      - 8080:8080 # Forward the exposed port 8080 on the container to port 8080 on the host machine
    links:
      - sms-postgres

  #Fron-end Angular Application
  frontend:
    image: "ajinkyadhote/sms-fs_frontend:v1"
    container_name: frontend
    ports:
      - 80:80
    links:
      - sms-backend

